import {
  Award,
  Banknote,
  BarChart3,
  Bell,
  BookMarked,
  BookOpen,
  Building2,
  Bus,
  CalendarCheck,
  CalendarOff,
  CalendarRange,
  ChartArea,
  ChartColumn,
  ChartLine,
  ChartPie,
  CircleAlert,
  ClipboardCheck,
  Clock,
  CreditCard,
  FileCheck,
  FileText,
  Fingerprint,
  Globe,
  GraduationCap,
  HeartHandshake,
  Landmark,
  LayoutDashboard,
  Lightbulb,
  Mail,
  MapPin,
  MessageSquare,
  MonitorSmartphone,
  MousePointerClick,
  Package,
  Palette,
  PenTool,
  Phone,
  Presentation,
  Rocket,
  ScanFace,
  ScanLine,
  School,
  ShieldCheck,
  Sparkles,
  Target,
  TrendingUp,
  Trophy,
  User,
  Users,
  Wallet,
  Wrench,
  Zap,
  BadgeCheck,
  CalendarDays,
  Clock3,
  Settings,
  Search,
  ListFilter,
  House,
  LoaderCircle,
  Ellipsis,
  CircleHelp,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  Award,
  Banknote,
  BarChart3,
  Bell,
  BookMarked,
  BookOpen,
  Building2,
  Bus,
  CalendarCheck,
  CalendarOff,
  CalendarRange,
  ChartArea,
  ChartColumn,
  ChartLine,
  ChartPie,
  CircleAlert,
  ClipboardCheck,
  Clock,
  CreditCard,
  FileCheck,
  FileText,
  Fingerprint,
  Globe,
  GraduationCap,
  HeartHandshake,
  Landmark,
  LayoutDashboard,
  Lightbulb,
  Mail,
  MapPin,
  MessageSquare,
  MonitorSmartphone,
  MousePointerClick,
  Package,
  Palette,
  PenTool,
  Phone,
  Presentation,
  Rocket,
  ScanFace,
  ScanLine,
  School,
  ShieldCheck,
  Sparkles,
  Target,
  TrendingUp,
  Trophy,
  User,
  Users,
  Wallet,
  Wrench,
  Zap,
  BadgeCheck,
  CalendarDays,
  Clock3,
  Settings,
  Search,
  ListFilter,
  House,
  LoaderCircle,
  Ellipsis,
  CircleHelp,
};

export interface DynamicIconProps {
  name: string;
  className?: string;
  size?: number | string;
  strokeWidth?: number;
}

export function DynamicIcon({ name, className, size = 20, strokeWidth = 2 }: DynamicIconProps) {
  const Icon = iconMap[name] ?? CircleHelp;
  return <Icon className={className} size={size} strokeWidth={strokeWidth} aria-hidden="true" />;
}
