name:sass build and deploy
on:
  push:
    branches:
      - main

env: 
  DOCKER_IMAGE_NAME: kavi8667/backend:sass 


jobs:
  build-and-test-job:
   
    runs-on: ubuntu-latest
    steps:
      -name: checkout code
       uses: actions/checkout@v2

      -name: set node
       uses: actions/setup-node@v2
       with: 
         node-version: 20
      - name: install dependencies
       run: npm install

       -name: build sass
       run: npm run build

       -name: build docker image
       run: docker build -t ${{env.DOCKER_IMAGE_NAME}} .

       -name: login to docker hub
       uses:docker/login-action@v2
       with:
        username:${{secrets.DOCKER_USERNAME}}
        password:${{secrets.DOCKER_PASSWORD}}

      -name: push docker image
       run: docker push ${{env.DOCKER_IMAGE_NAME}}
  
  
  deploy-job:
    needs: build-and-test-job
    runs-on: ubuntu-latest

    steps:
      -name: server ssh  login panna
      uses: appleboy/ssh-action@v1
        with:
          host: ${{vars.HOST_IP}}
          username: ec-user
          key: ${{ secrets.AWS_EC2_KEY }}
          port: 22
          script: |
             docker pull ${{env.DOCKER_IMAGE_NAME}}


            